language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip3 install -e .
  - pip3 install git+https://github.com/openai/gym.git@0.25.0

# command to run tests
script: ./run_tests.py
