language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip3 install -e .
  - pip3 install git+https://github.com/pseudo-rnd-thoughts/gym.git@fixed-env-checker
  - pip3 install gym[others]

# command to run tests
script: ./run_tests.py
